### ISSUE TITLE
Credit Card Issue when Logged in

### ISSUE THREAD

**Issue by Shivoxx1337** [wirecard/woocommerce-ee#396]
### Prerequisites

- [ ] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [ ] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version:** 4.2.0
**PHP version:** 7.2  

### Issue

**Problem description:**

When im logged in the Creditcard form dont show up when im logged out its working as intended 
Ive tried previous versions of the plugin  and tried it on a stagging area with all plugins disabled  but still dosent solve the issue 

**Steps to reproduce:**

...

**Comment by ozada** [comment]
Hi @Shivoxx1337!
Thanks for your feedback. On the version 4.2.0 we don't encounter the issue. Can you describe exactly steps to reproduce it.

Kind Regards,
Shopsystems Team @ Wirecard

**Comment by Shivoxx1337** [comment]
Hi Oskar,
I'm already in touch with the Austrian  Costumer Support.
http://prntscr.com/t02dhs [http://prntscr.com/t02dhs]

The iFrame dosent load i think it has something to do with the latest wordpress version. 
We tried it on a stagging area and disabled all other Plugins and it  still dosent work.

Kind regards
Gregor.
Am 15.06.2020 16:39:17 schrieb Oskar H. Zada <notifications@github.com>:
Hi @Shivoxx1337 [https://github.com/Shivoxx1337]!
Thanks for your feedback. On the version 4.2.0 we don't encounter the issue. Can you describe exactly steps to reproduce it.
Kind Regards,
Shopsystems Team @ Wirecard

**Comment by Shivoxx1337** [comment]
additional info: We're using WordPress 5.4.2 

kind Regards
Gregor.
Am 15.06.2020 16:42:22 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Hi Oskar,
I'm already in touch with the Austrian  Costumer Support.
http://prntscr.com/t02dhs [http://prntscr.com/t02dhs]

The iFrame dosent load i think it has something to do with the latest wordpress version. 
We tried it on a stagging area and disabled all other Plugins and it  still dosent work.

Kind regards
Gregor.
Am 15.06.2020 16:39:17 schrieb Oskar H. Zada <notifications@github.com>:
Hi @Shivoxx1337 [https://github.com/Shivoxx1337]!
Thanks for your feedback. On the version 4.2.0 we don't encounter the issue. Can you describe exactly steps to reproduce it.
Kind Regards,
Shopsystems Team @ Wirecard

**Comment by ozada** [comment]
@Shivoxx1337 Thank you for the provided details. We have already checked the described combination of versions: (WP:5.4.2(latest) / WOO:4.2.0 (latest) / WD: 3.3.0 (latest)). It is still not reproducible. Could you please check server side logs and JS console logs and if something strange happens please share it with us.

Kind Regards,
Shopsystems Team @ Wirecard

**Comment by Shivoxx1337** [comment]
Hi,
There is nothing strange in the Logs if you want i cant provide you Login Creditinals to WordPress to live site or to a stagging area to reproduce this issue?

Kind Regards
Gregor.
Am 15.06.2020 17:17:38 schrieb Oskar H. Zada <notifications@github.com>:
@Shivoxx1337 [https://github.com/Shivoxx1337] Thank you for the provided details. We have already checked the described combination of versions: (WP:5.4.2(latest) / WOO:4.2.0 (latest) / WD: 3.3.0 (latest)). It is still not reproducible. Could you please check server side logs and JS console logs and if something strange happens please share it with us.
Kind Regards,
Shopsystems Team @ Wirecard

**Comment by Shivoxx1337** [comment]
Im going to add few more things  what  is tested and what not
Thats our Site juliana-nails.com you can try it yourself here and see what happens.
Like ive written before we've disabled all plugins switched to standard theme  but its not working on the stagging site with all that stuff deactivated.
we've also tried all the different PHP versions but still not working :(

kind Regards
Gregor.
Am 15.06.2020 17:24:38 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Hi,
There is nothing strange in the Logs if you want i cant provide you Login Creditinals to WordPress to live site or to a stagging area to reproduce this issue?

Kind Regards
Gregor.
Am 15.06.2020 17:17:38 schrieb Oskar H. Zada <notifications@github.com>:
@Shivoxx1337 [https://github.com/Shivoxx1337] Thank you for the provided details. We have already checked the described combination of versions: (WP:5.4.2(latest) / WOO:4.2.0 (latest) / WD: 3.3.0 (latest)). It is still not reproducible. Could you please check server side logs and JS console logs and if something strange happens please share it with us.
Kind Regards,
Shopsystems Team @ Wirecard

**Comment by Shivoxx1337** [comment]
Additional Information Ive created a completly new site
With 5.4.2 running Standard Theme WooCommerce and Wirecard Plugin its not working
I also switched back to 5.3.2 to see if this would solve the issue.
Date Message Extra
16:57 PM 15 Jun
Custom Log: [2020-06-15 16:57:44] wirecard_payment_sdk.DEBUG: Seamless request body: {"request_time_stamp":"20200615165744","request_id":"8e5c81911c496d80beccc6c16f49df111833800a0e7502ed3b91a0080b455ebe","transaction_type":"purchase","merchant_account_id":"53f2895a-e4de-4e82-a813-0d87a10e55e6","requested_amount":50,"requested_amount_currency":"EUR","locale":"en","payment_method":"creditcard","attempt_three_d":false,"shop_system_name":"WooCommerce","shop_system_version":"4.2.0+WordPress+5.3.4","plugin_name":"woocommerce-ee+Wirecard","plugin_version":"3.1.0","email":"gregor.cesal@gmail.com","phone":"+436766904885","city":"Wien","country":"AT","postal_code":"1200","street1":"Vorgartenstra\u00dfe 103\/1","authentication_method":"01","authentication_timestamp":"2020-06-15T16:57:44Z","challenge_indicator":"01","shipping_city":"","shipping_country":"","shipping_postal_code":"","orderItems1.name":"test 123","orderItems1.quantity":1,"orderItems1.amount.value":50,"orderItems1.amount.currency":"EUR","orderItems1.articleNumber":10,"orderItems1.taxRate":0,"field_name_1":"paysdk_orderId","field_value_1":12,"field_name_2":"paysdk_multisite","field_value_2":"","field_name_3":"paysdk_phpVersion","field_value_3":"7.2.31","success_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=12&payment-state=success&payment-method=creditcard","cancel_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=12&payment-state=cancel&payment-method=creditcard","fail_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=12&payment-state=failure&payment-method=creditcard","risk_info_delivery_mail":"gregor.cesal@gmail.com","notification_transaction_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway&payment-method=creditcard&order-id=12","notifications_format":"application\/xml","descriptor":"irecardT12","order_number":"12","ip_address":"62.178.252.67","consumer_id":0,"iso_transaction_type":"01","request_signature":"19f2e73e2d27651bdaeef22531c5c4de202f1444dac716363a28ead43a821676"} [] []
16:57 PM 15 Jun
Custom Log: [2020-06-15 16:57:05] wirecard_payment_sdk.DEBUG: Seamless request body: {"request_time_stamp":"20200615165705","request_id":"068085cebdb143617f021db69142bb298afef4fdd55a156606650cd6b7bfeddb","transaction_type":"purchase","merchant_account_id":"53f2895a-e4de-4e82-a813-0d87a10e55e6","requested_amount":50,"requested_amount_currency":"EUR","locale":"en","payment_method":"creditcard","attempt_three_d":false,"shop_system_name":"WooCommerce","shop_system_version":"4.2.0+WordPress+5.3.4","plugin_name":"woocommerce-ee+Wirecard","plugin_version":"3.1.0","email":"gregor.cesal@gmail.com","phone":"+496766904885","city":"Ivanic Grad","country":"AT","postal_code":"1200","street1":"Franje Jurinca","street2":"18","merchant_crm_id":"1","authentication_method":"02","authentication_timestamp":"2020-06-15T16:57:05Z","challenge_indicator":"01","account_creation_date":"2020-06-15","account_update_date":"2020-06-15","shipping_address_first_use":"2020-06-15","card_creation_date":"2020-06-15","purchases_last_six_months":0,"shipping_city":"","shipping_country":"","shipping_postal_code":"","orderItems1.name":"test 123","orderItems1.quantity":1,"orderItems1.amount.value":50,"orderItems1.amount.currency":"EUR","orderItems1.articleNumber":10,"orderItems1.taxRate":0,"field_name_1":"paysdk_orderId","field_value_1":11,"field_name_2":"paysdk_multisite","field_value_2":"","field_name_3":"paysdk_phpVersion","field_value_3":"7.2.31","success_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=11&payment-state=success&payment-method=creditcard","cancel_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=11&payment-state=cancel&payment-method=creditcard","fail_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=11&payment-state=failure&payment-method=creditcard","risk_info_delivery_mail":"gregor.cesal@gmail.com","notification_transaction_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway&payment-method=creditcard&order-id=11","notifications_format":"application\/xml","descriptor":"irecardT11","order_number":"11","ip_address":"62.178.252.67","consumer_id":1,"iso_transaction_type":"01","request_signature":"9a43143950a4cc6e5b442281b63ca6c1273b6fb055186d96f7a6162bccfbcb73"} [] []

I got this 2 Errors.

Kind Regards
Gregor.
Am 15.06.2020 18:20:11 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Im going to add few more things  what  is tested and what not
Thats our Site juliana-nails.com you can try it yourself here and see what happens.
Like ive written before we've disabled all plugins switched to standard theme  but its not working on the stagging site with all that stuff deactivated.
we've also tried all the different PHP versions but still not working :(

kind Regards
Gregor.
Am 15.06.2020 17:24:38 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Hi,
There is nothing strange in the Logs if you want i cant provide you Login Creditinals to WordPress to live site or to a stagging area to reproduce this issue?

Kind Regards
Gregor.
Am 15.06.2020 17:17:38 schrieb Oskar H. Zada <notifications@github.com>:
@Shivoxx1337 [https://github.com/Shivoxx1337] Thank you for the provided details. We have already checked the described combination of versions: (WP:5.4.2(latest) / WOO:4.2.0 (latest) / WD: 3.3.0 (latest)). It is still not reproducible. Could you please check server side logs and JS console logs and if something strange happens please share it with us.
Kind Regards,
Shopsystems Team @ Wirecard

**Comment by Shivoxx1337** [comment]
Hi Again,
Ive also checked now on livesite .
and there is the same code:
Custom Log: [2020-06-15 20:56:44] wirecard_payment_sdk.DEBUG: Seamless request body: {"request_time_stamp":"20200615205644","request_id":"1fefd3029c0b87bb6f441a1fc3ef51c91343157d8fb4e710e935b7ba02433fbd","transaction_type":"purchase","merchant_account_id":"53f2895a-e4de-4e82-a813-0d87a10e55e6","requested_amount":12.800000000000000710542735760100185871124267578125,"requested_amount_currency":"EUR","locale":"de","payment_method":"creditcard","attempt_three_d":false,"shop_system_name":"WooCommerce","shop_system_version":"4.2.0+WordPress+5.4.2","plugin_name":"woocommerce-ee+Wirecard","plugin_version":"3.1.0","email":"gregor.cesal@gmail.com","phone":"+43 664 544 19 80","city":"Klagenfurt am W\u00f6rthersee","country":"AT","postal_code":"9020","street1":"Gerberweg 71","street2":"41","merchant_crm_id":"1","authentication_method":"02","authentication_timestamp":"2020-06-15T20:56:44Z","challenge_indicator":"01","account_creation_date":"2019-06-28","account_update_date":"2020-06-15","shipping_address_first_use":"2020-04-21","card_creation_date":"2020-06-15","purchases_last_six_months":12,"shipping_city":"Klagenfurt am W\u00f6rthersee","shipping_country":"AT","shipping_postal_code":"9020","shipping_street1":"Gerberweg 71","orderItems1.name":"Gel Lack Luxury Baby Pink 6ml","orderItems1.quantity":1,"orderItems1.amount.value":7.9000000000000003552713678800500929355621337890625,"orderItems1.amount.currency":"EUR","orderItems1.articleNumber":577695,"orderItems1.taxRate":20,"orderItems2.name":"Shipping","orderItems2.quantity":1,"orderItems2.amount.value":4.9000000000000003552713678800500929355621337890625,"orderItems2.amount.currency":"EUR","orderItems2.articleNumber":"Shipping","orderItems2.taxRate":20,"field_name_1":"paysdk_orderId","field_value_1":578174,"field_name_2":"paysdk_multisite","field_value_2":"","field_name_3":"paysdk_phpVersion","field_value_3":"7.2.28","success_redirect_url":"https:\/\/juliana-nails.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=578174&payment-state=success&payment-method=creditcard","cancel_redirect_url":"https:\/\/juliana-nails.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=578174&payment-state=cancel&payment-method=creditcard","fail_redirect_url":"https:\/\/juliana-nails.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=578174&payment-state=failure&payment-method=creditcard","risk_info_delivery_mail":"gregor.cesal@gmail.com","notification_transaction_url":"https:\/\/juliana-nails.com\/?wc-api=WC_Wirecard_Payment_Gateway&payment-method=creditcard&order-id=578174","notifications_format":"application\/xml","descriptor":"JulianaN578174","order_number":"578174","ip_address":"62.178.252.67","consumer_id":1,"iso_transaction_type":"01","request_signature":"2329935414ee8889b4a790af5f37c26e6198d3a5549a05c6574e7fd9799ea92b"} [] []


Kind Regards
Gregor.
Am 15.06.2020 18:59:44 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Additional Information Ive created a completly new site
With 5.4.2 running Standard Theme WooCommerce and Wirecard Plugin its not working
I also switched back to 5.3.2 to see if this would solve the issue.
Date Message Extra
16:57 PM 15 Jun
Custom Log: [2020-06-15 16:57:44] wirecard_payment_sdk.DEBUG: Seamless request body: {"request_time_stamp":"20200615165744","request_id":"8e5c81911c496d80beccc6c16f49df111833800a0e7502ed3b91a0080b455ebe","transaction_type":"purchase","merchant_account_id":"53f2895a-e4de-4e82-a813-0d87a10e55e6","requested_amount":50,"requested_amount_currency":"EUR","locale":"en","payment_method":"creditcard","attempt_three_d":false,"shop_system_name":"WooCommerce","shop_system_version":"4.2.0+WordPress+5.3.4","plugin_name":"woocommerce-ee+Wirecard","plugin_version":"3.1.0","email":"gregor.cesal@gmail.com","phone":"+436766904885","city":"Wien","country":"AT","postal_code":"1200","street1":"Vorgartenstra\u00dfe 103\/1","authentication_method":"01","authentication_timestamp":"2020-06-15T16:57:44Z","challenge_indicator":"01","shipping_city":"","shipping_country":"","shipping_postal_code":"","orderItems1.name":"test 123","orderItems1.quantity":1,"orderItems1.amount.value":50,"orderItems1.amount.currency":"EUR","orderItems1.articleNumber":10,"orderItems1.taxRate":0,"field_name_1":"paysdk_orderId","field_value_1":12,"field_name_2":"paysdk_multisite","field_value_2":"","field_name_3":"paysdk_phpVersion","field_value_3":"7.2.31","success_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=12&payment-state=success&payment-method=creditcard","cancel_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=12&payment-state=cancel&payment-method=creditcard","fail_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=12&payment-state=failure&payment-method=creditcard","risk_info_delivery_mail":"gregor.cesal@gmail.com","notification_transaction_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway&payment-method=creditcard&order-id=12","notifications_format":"application\/xml","descriptor":"irecardT12","order_number":"12","ip_address":"62.178.252.67","consumer_id":0,"iso_transaction_type":"01","request_signature":"19f2e73e2d27651bdaeef22531c5c4de202f1444dac716363a28ead43a821676"} [] []
16:57 PM 15 Jun
Custom Log: [2020-06-15 16:57:05] wirecard_payment_sdk.DEBUG: Seamless request body: {"request_time_stamp":"20200615165705","request_id":"068085cebdb143617f021db69142bb298afef4fdd55a156606650cd6b7bfeddb","transaction_type":"purchase","merchant_account_id":"53f2895a-e4de-4e82-a813-0d87a10e55e6","requested_amount":50,"requested_amount_currency":"EUR","locale":"en","payment_method":"creditcard","attempt_three_d":false,"shop_system_name":"WooCommerce","shop_system_version":"4.2.0+WordPress+5.3.4","plugin_name":"woocommerce-ee+Wirecard","plugin_version":"3.1.0","email":"gregor.cesal@gmail.com","phone":"+496766904885","city":"Ivanic Grad","country":"AT","postal_code":"1200","street1":"Franje Jurinca","street2":"18","merchant_crm_id":"1","authentication_method":"02","authentication_timestamp":"2020-06-15T16:57:05Z","challenge_indicator":"01","account_creation_date":"2020-06-15","account_update_date":"2020-06-15","shipping_address_first_use":"2020-06-15","card_creation_date":"2020-06-15","purchases_last_six_months":0,"shipping_city":"","shipping_country":"","shipping_postal_code":"","orderItems1.name":"test 123","orderItems1.quantity":1,"orderItems1.amount.value":50,"orderItems1.amount.currency":"EUR","orderItems1.articleNumber":10,"orderItems1.taxRate":0,"field_name_1":"paysdk_orderId","field_value_1":11,"field_name_2":"paysdk_multisite","field_value_2":"","field_name_3":"paysdk_phpVersion","field_value_3":"7.2.31","success_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=11&payment-state=success&payment-method=creditcard","cancel_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=11&payment-state=cancel&payment-method=creditcard","fail_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=11&payment-state=failure&payment-method=creditcard","risk_info_delivery_mail":"gregor.cesal@gmail.com","notification_transaction_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway&payment-method=creditcard&order-id=11","notifications_format":"application\/xml","descriptor":"irecardT11","order_number":"11","ip_address":"62.178.252.67","consumer_id":1,"iso_transaction_type":"01","request_signature":"9a43143950a4cc6e5b442281b63ca6c1273b6fb055186d96f7a6162bccfbcb73"} [] []

I got this 2 Errors.

Kind Regards
Gregor.
Am 15.06.2020 18:20:11 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Im going to add few more things  what  is tested and what not
Thats our Site juliana-nails.com you can try it yourself here and see what happens.
Like ive written before we've disabled all plugins switched to standard theme  but its not working on the stagging site with all that stuff deactivated.
we've also tried all the different PHP versions but still not working :(

kind Regards
Gregor.
Am 15.06.2020 17:24:38 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Hi,
There is nothing strange in the Logs if you want i cant provide you Login Creditinals to WordPress to live site or to a stagging area to reproduce this issue?

Kind Regards
Gregor.
Am 15.06.2020 17:17:38 schrieb Oskar H. Zada <notifications@github.com>:
@Shivoxx1337 [https://github.com/Shivoxx1337] Thank you for the provided details. We have already checked the described combination of versions: (WP:5.4.2(latest) / WOO:4.2.0 (latest) / WD: 3.3.0 (latest)). It is still not reproducible. Could you please check server side logs and JS console logs and if something strange happens please share it with us.
Kind Regards,
Shopsystems Team @ Wirecard

**Comment by Shivoxx1337** [comment]
Hi this is the last time for today
#0 /home/5cfe00e3f911c80f5082263e/public_html/wp-content/plugins/wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-ideal.php(77): WC_Gateway_Wirecard_Ideal->init_form_fields() #1 /home/5cfe00e3f911c80f5082263e/public_html/wp-content/plugins/wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php(190): WC_Gateway_Wirecard_Ideal->__construct() #2 /home/5cfe00e3f911c80f5082263e/public_html/wp-content/plugins/wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php(159): wirecard_get_payments() #3 /home/5cfe00e3f911c80f5082263e/public_html/wp-includes/class-wp-hook.php(287): wirecard_add_payment_gateway(Array) #4 /home/5cfe00e3f911c80f5082263e/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
Am 15.06.2020 23:02:54 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Hi Again,
Ive also checked now on livesite .
and there is the same code:
Custom Log: [2020-06-15 20:56:44] wirecard_payment_sdk.DEBUG: Seamless request body: {"request_time_stamp":"20200615205644","request_id":"1fefd3029c0b87bb6f441a1fc3ef51c91343157d8fb4e710e935b7ba02433fbd","transaction_type":"purchase","merchant_account_id":"53f2895a-e4de-4e82-a813-0d87a10e55e6","requested_amount":12.800000000000000710542735760100185871124267578125,"requested_amount_currency":"EUR","locale":"de","payment_method":"creditcard","attempt_three_d":false,"shop_system_name":"WooCommerce","shop_system_version":"4.2.0+WordPress+5.4.2","plugin_name":"woocommerce-ee+Wirecard","plugin_version":"3.1.0","email":"gregor.cesal@gmail.com","phone":"+43 664 544 19 80","city":"Klagenfurt am W\u00f6rthersee","country":"AT","postal_code":"9020","street1":"Gerberweg 71","street2":"41","merchant_crm_id":"1","authentication_method":"02","authentication_timestamp":"2020-06-15T20:56:44Z","challenge_indicator":"01","account_creation_date":"2019-06-28","account_update_date":"2020-06-15","shipping_address_first_use":"2020-04-21","card_creation_date":"2020-06-15","purchases_last_six_months":12,"shipping_city":"Klagenfurt am W\u00f6rthersee","shipping_country":"AT","shipping_postal_code":"9020","shipping_street1":"Gerberweg 71","orderItems1.name":"Gel Lack Luxury Baby Pink 6ml","orderItems1.quantity":1,"orderItems1.amount.value":7.9000000000000003552713678800500929355621337890625,"orderItems1.amount.currency":"EUR","orderItems1.articleNumber":577695,"orderItems1.taxRate":20,"orderItems2.name":"Shipping","orderItems2.quantity":1,"orderItems2.amount.value":4.9000000000000003552713678800500929355621337890625,"orderItems2.amount.currency":"EUR","orderItems2.articleNumber":"Shipping","orderItems2.taxRate":20,"field_name_1":"paysdk_orderId","field_value_1":578174,"field_name_2":"paysdk_multisite","field_value_2":"","field_name_3":"paysdk_phpVersion","field_value_3":"7.2.28","success_redirect_url":"https:\/\/juliana-nails.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=578174&payment-state=success&payment-method=creditcard","cancel_redirect_url":"https:\/\/juliana-nails.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=578174&payment-state=cancel&payment-method=creditcard","fail_redirect_url":"https:\/\/juliana-nails.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=578174&payment-state=failure&payment-method=creditcard","risk_info_delivery_mail":"gregor.cesal@gmail.com","notification_transaction_url":"https:\/\/juliana-nails.com\/?wc-api=WC_Wirecard_Payment_Gateway&payment-method=creditcard&order-id=578174","notifications_format":"application\/xml","descriptor":"JulianaN578174","order_number":"578174","ip_address":"62.178.252.67","consumer_id":1,"iso_transaction_type":"01","request_signature":"2329935414ee8889b4a790af5f37c26e6198d3a5549a05c6574e7fd9799ea92b"} [] []


Kind Regards
Gregor.
Am 15.06.2020 18:59:44 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Additional Information Ive created a completly new site
With 5.4.2 running Standard Theme WooCommerce and Wirecard Plugin its not working
I also switched back to 5.3.2 to see if this would solve the issue.
Date Message Extra
16:57 PM 15 Jun
Custom Log: [2020-06-15 16:57:44] wirecard_payment_sdk.DEBUG: Seamless request body: {"request_time_stamp":"20200615165744","request_id":"8e5c81911c496d80beccc6c16f49df111833800a0e7502ed3b91a0080b455ebe","transaction_type":"purchase","merchant_account_id":"53f2895a-e4de-4e82-a813-0d87a10e55e6","requested_amount":50,"requested_amount_currency":"EUR","locale":"en","payment_method":"creditcard","attempt_three_d":false,"shop_system_name":"WooCommerce","shop_system_version":"4.2.0+WordPress+5.3.4","plugin_name":"woocommerce-ee+Wirecard","plugin_version":"3.1.0","email":"gregor.cesal@gmail.com","phone":"+436766904885","city":"Wien","country":"AT","postal_code":"1200","street1":"Vorgartenstra\u00dfe 103\/1","authentication_method":"01","authentication_timestamp":"2020-06-15T16:57:44Z","challenge_indicator":"01","shipping_city":"","shipping_country":"","shipping_postal_code":"","orderItems1.name":"test 123","orderItems1.quantity":1,"orderItems1.amount.value":50,"orderItems1.amount.currency":"EUR","orderItems1.articleNumber":10,"orderItems1.taxRate":0,"field_name_1":"paysdk_orderId","field_value_1":12,"field_name_2":"paysdk_multisite","field_value_2":"","field_name_3":"paysdk_phpVersion","field_value_3":"7.2.31","success_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=12&payment-state=success&payment-method=creditcard","cancel_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=12&payment-state=cancel&payment-method=creditcard","fail_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=12&payment-state=failure&payment-method=creditcard","risk_info_delivery_mail":"gregor.cesal@gmail.com","notification_transaction_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway&payment-method=creditcard&order-id=12","notifications_format":"application\/xml","descriptor":"irecardT12","order_number":"12","ip_address":"62.178.252.67","consumer_id":0,"iso_transaction_type":"01","request_signature":"19f2e73e2d27651bdaeef22531c5c4de202f1444dac716363a28ead43a821676"} [] []
16:57 PM 15 Jun
Custom Log: [2020-06-15 16:57:05] wirecard_payment_sdk.DEBUG: Seamless request body: {"request_time_stamp":"20200615165705","request_id":"068085cebdb143617f021db69142bb298afef4fdd55a156606650cd6b7bfeddb","transaction_type":"purchase","merchant_account_id":"53f2895a-e4de-4e82-a813-0d87a10e55e6","requested_amount":50,"requested_amount_currency":"EUR","locale":"en","payment_method":"creditcard","attempt_three_d":false,"shop_system_name":"WooCommerce","shop_system_version":"4.2.0+WordPress+5.3.4","plugin_name":"woocommerce-ee+Wirecard","plugin_version":"3.1.0","email":"gregor.cesal@gmail.com","phone":"+496766904885","city":"Ivanic Grad","country":"AT","postal_code":"1200","street1":"Franje Jurinca","street2":"18","merchant_crm_id":"1","authentication_method":"02","authentication_timestamp":"2020-06-15T16:57:05Z","challenge_indicator":"01","account_creation_date":"2020-06-15","account_update_date":"2020-06-15","shipping_address_first_use":"2020-06-15","card_creation_date":"2020-06-15","purchases_last_six_months":0,"shipping_city":"","shipping_country":"","shipping_postal_code":"","orderItems1.name":"test 123","orderItems1.quantity":1,"orderItems1.amount.value":50,"orderItems1.amount.currency":"EUR","orderItems1.articleNumber":10,"orderItems1.taxRate":0,"field_name_1":"paysdk_orderId","field_value_1":11,"field_name_2":"paysdk_multisite","field_value_2":"","field_name_3":"paysdk_phpVersion","field_value_3":"7.2.31","success_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=11&payment-state=success&payment-method=creditcard","cancel_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=11&payment-state=cancel&payment-method=creditcard","fail_redirect_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway_Redirect&order-id=11&payment-state=failure&payment-method=creditcard","risk_info_delivery_mail":"gregor.cesal@gmail.com","notification_transaction_url":"https:\/\/app-5edfa4e4c1ac1a0f6086b558.closte.com\/?wc-api=WC_Wirecard_Payment_Gateway&payment-method=creditcard&order-id=11","notifications_format":"application\/xml","descriptor":"irecardT11","order_number":"11","ip_address":"62.178.252.67","consumer_id":1,"iso_transaction_type":"01","request_signature":"9a43143950a4cc6e5b442281b63ca6c1273b6fb055186d96f7a6162bccfbcb73"} [] []

I got this 2 Errors.

Kind Regards
Gregor.
Am 15.06.2020 18:20:11 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Im going to add few more things  what  is tested and what not
Thats our Site juliana-nails.com you can try it yourself here and see what happens.
Like ive written before we've disabled all plugins switched to standard theme  but its not working on the stagging site with all that stuff deactivated.
we've also tried all the different PHP versions but still not working :(

kind Regards
Gregor.
Am 15.06.2020 17:24:38 schrieb gregor.cesal@gmail.com <gregor.cesal@gmail.com>:
Hi,
There is nothing strange in the Logs if you want i cant provide you Login Creditinals to WordPress to live site or to a stagging area to reproduce this issue?

Kind Regards
Gregor.
Am 15.06.2020 17:17:38 schrieb Oskar H. Zada <notifications@github.com>:
@Shivoxx1337 [https://github.com/Shivoxx1337] Thank you for the provided details. We have already checked the described combination of versions: (WP:5.4.2(latest) / WOO:4.2.0 (latest) / WD: 3.3.0 (latest)). It is still not reproducible. Could you please check server side logs and JS console logs and if something strange happens please share it with us.
Kind Regards,
Shopsystems Team @ Wirecard

**Comment by Shivoxx1337** [comment]
PHP Fatal error: Uncaught Error: Call to a member function get_id() on bool in /wp-content/plugins/wirecard-woocommerce-extension/classes/includes/class-wc-wirecard-payment-gateway.php:318

**Comment by vitali-graz** [comment]
Hi @Shivoxx1337 
Thank you for providing detailed information.
Since you are already in contact with our support, please stick to that channel to limit the touchpoints.

In addition, please do not share your merchant config data on GitHub! Only in direct communication with the support.

Best regards,
Wirecard Shop Extensions Team

**Comment by Shivoxx1337** [comment]
Hi Vitali,
Please let me know when you have all that stuff that you need then im going to delete the posts above.

Kind Regards
Gregor.

**Comment by vitali-graz** [comment]
Hi Gregor,
If you have shared the same information with our support, then we already have everything.
Best regards,
Vitali

**Comment by Shivoxx1337** [comment]
Hi vitali,
I have it only shared with you here on github not with the support itself.

Kind Regards
Gregor.
Am 16.06.2020 15:25:07 schrieb Vitali Auracher <notifications@github.com>:
Hi Gregor,
If you have shared the same information with our support, then we already have everything.
Best regards,
Vitali

**Comment by Shivoxx1337** [comment]
HI
Now its even not working even when  im logged out.
Kind  Regards
Gregor.
